### ISSUE TITLE
Enabling OAuth for Studio login

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#101]
## Description

[DEPR-166](https://openedx.atlassian.net/browse/DEPR-166?focusedCommentId=568620&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-568620) introduces code and configuration changes on master to give Studio a separate session and cookie (scoped to just the Studio domain) and plan to reduce the domain scope of LMS's session cookie as well. studio.edx.org now performs an OAuth login flow against the LMS, just like other IDAs do. 

## Acceptance criteria

A PR to tutor master is merged with the [configuration required](https://github.com/edx/edx-platform/blob/master/docs/guides/studio_oauth.rst).

## Estimated effort
2 hours of a developer experienced with the tutor installation

## Bounties
N/A

**Comment by regisb** [comment]
@timmc-edx to automatically create OAuth2 provider applications in Tutor, we make use of the [create_dot_application](https://github.com/edx/edx-platform/blob/open-release/maple.master/openedx/core/djangoapps/oauth_dispatch/management/commands/create_dot_application.py) management command. However, this command does not allow us to pass an empty "user", as you recommend in the [studio oauth guide](https://github.com/edx/edx-platform/blob/master/docs/guides/studio_oauth.rst). This means that we need to create a "cms" user beforehand, with:

   ./manage.py lms manage_user cms cms@openedx --unusable-password

And then associate this user to the application with:

```
./manage.py lms create_dot_application \
  --grant-type authorization-code \
  --redirect-uris "https://studio.maple.openedx.overhang.io/complete/edx-oauth2/" \
  --client-id cms-sso \
  --client-secret mysecret \
  --scopes user_id \
  --skip-authorization \
  --update cms-sso cms
```

Is that an issue? If yes, could you please modify the `create_dot_application` command to make the "username" argument optional?

**Comment by timmc-edx** [comment]
(OK, ignore all that nonsense I posted before... let's try this again now that I'm back up to speed on this.)

Yes, we should probably create a `studio_worker` user, just because all the other apps have one. I'm not actually sure what the difference is between having/not having a user associated with a DOT client. The docs refer to it as the "owner" but I don't know what that implies.

Rather than cms, I'd suggest using the name `studio_worker` for the service account and `studio-sso` for the client name, for consistency with devstack and the way we seem to be using "studio" more often than "cms" (likely because it's easier to visually distinguish).

On the cookie domain, I'd recommend narrowing `SESSION_COOKIE_DOMAIN`. You're correct that `SHARED_COOKIE_DOMAIN` should stay broad.

**Comment by regisb** [comment]
Hi @timmc-edx! Our modification of `SESSION_COOKIE_DOMAIN` is breaking preview site authentication for people who do not run their preview site under a subdomain of the LMS. Could you please pitch in here? https://github.com/overhangio/tutor/issues/557
