### ISSUE TITLE
User Testing of Maple

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#124]
User Testing of Maple.

[LMS](lms.maple-btr.edunext.link)
[Studio](studio.maple-btr.edunext.link)
[ecommerce.lms.maple-btr.edunext.link](ecommerce.lms.maple-btr.edunext.link)
[MFE](apps.lms.maple-btr.edunext.link)

Once you've created an account comment here and we will give you any permissions you need.

PR for the release notes, if you have any specific comments: https://github.com/edx/edx-documentation/pull/1994

**Comment by gabrieldamours** [comment]
I'm in to do some testing

**Comment by ghassanmas** [comment]
Maple instance without e-commerce (for now) http://edx.gsgapp.io

**Comment by antoviaque** [comment]
Me too!

**Comment by felipemontoya** [comment]
@antoviaque I thought nobody was testing anylonger since the ecommerce issue was solved so I turned the VM off. I just turned it on again so you can go ahead and test.

**Comment by ghassanmas** [comment]
@antoviaque I have just fixed the problem of not being able to post:

**Cause**: The follwoing Elasticseach.as it turns out elastic seach delibiatry stopps writting when disk space is less than 1 giga I guess.
**Fix**: I just had to clear up some spaces. e.g. clear docker/tutor images caches. 

Error for reference:
`Elasticsearch error: cluster_block_exception [FORBIDDEN/12/index read-only / allow delete (api)], flood stage disk watermark exceeded` That caused the forum to fail. 

**Note**: most imporatnly this seems to be a problem relative to my dev enviroment not something to do with maple or not related to past problem we had resolved with fourm. 

As for the layout or the broken element I am not sure how that suppose to be, humm

**Comment by antoviaque** [comment]
@felipemontoya Thanks! I have created an account on it (`antoviaque`) -- however I don't seem to be receiving the activation email. 

Also, when I try to connect to Studio, by clicking "Sign in" on https://studio.maple-btr.edunext.link/ I get a redirect error to https://studio.maple-btr.edunext.link/login/?next=https%3A//studio.maple-btr.edunext.link/ -- it looks like a redirect loop?

![image](https://user-images.githubusercontent.com/514483/146484350-6fb1f819-2a52-4d1a-88b8-0a627577e6dc.png)

Admin or course creation rights would also be useful for some of the testing.

**Comment by ghassanmas** [comment]
@antoviaque I have made you super user and staff member. You should be able to login studio.edx.gsgapp.io and on Django admin

**Comment by antoviaque** [comment]
@ghassanmas Thank you! I was able to create and edit a course and a library in Studio yes.

One issue I saw is with the login flow from Studio -- it's probably just a configuration thing, but since this is one of the parts that have changed with Maple I'm mentioning it:
* Go to
* Click on sign in, which brings to the LMS login page
* Enter email & password
* => Nothing happens

In the console, the POST succeeds, but then it the JS fails on _"Uncaught TypeError: can't access property "replace", n is null"_:

![image](https://user-images.githubusercontent.com/514483/146601928-fcea9b41-9fe0-4581-b1e8-66821c9b14b4.png)

Refreshing shows that I'm successfully logged in on the LMS side, but refreshing or going back to the Studio homepage to click "sign in" gives the error _"Error: invalid_request Mismatching redirect URI."_

![image](https://user-images.githubusercontent.com/514483/146602215-fadac195-c401-4102-9a2d-646814dc1886.png)

I am however still logged in when I go to http://studio.edx.gsgapp.io/home/

My browser: https://whatsmybrowser.org/b/CKF4D

**Comment by regisb** [comment]
This should now be resolved in the maple branch of Tutor: https://github.com/openedx/build-test-release-wg/issues/104

**Comment by ghassanmas** [comment]
@regisb you mean maple beta 2?

**Comment by ghassanmas** [comment]
Aha I see you commited something recently here https://github.com/overhangio/tutor/commit/729c2d4ec665ecec2b42fd1d7474dc4f3e383c20 , will pull and return tutor soon

**Comment by gabrieldamours** [comment]
@ghassanmas I've also created an account for testing purposes, with my email gabriel [at] opencraft.com. Can you please make me an admin? Thx!

**Comment by ghassanmas** [comment]
@gabrieldamours I have made me an admin and super user since yesterday in case you aren't already aware. 

On the other hand, I plan to redeploy the new beta release by tomorrow, which should resolve @antoviaque reported issue.as stated by @regisb. ( I will write to this thread when the new release is available)

**Comment by ghassanmas** [comment]
I have just deployed the master of tutor which has tutor version 13.0.2 
The system is running by fast check, though the issue reported by @antoviaque earlier which @regisb metion should be resolved wasn't. Not sure if tutor master branch should resolve it
Anyway Merry Christams everyone 🎅
