### ISSUE TITLE
TC_AUTHOR_64 > Studio > Xblock > freetextresponse > Xblock is not appearing under advance xblock list

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#161]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click on add unit
4. Go to advance setting under settings dropdown and then add "freetextresponse" in the list and save it
5. Check freetextresponse xblock under advance xblocks list
**Expected result:**
Xblock should be available under advance xblock list
**Actual result:**
Xblock is not available under advance xblock list

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by sambapete** [comment]
This is not one the system's default XBlock. It might need to be installed on the system.

**Comment by DeanJayMathew** [comment]
Thank you for adding this to the Nutmeg milestones Sofiane. 

@regisb is this freetextresponse not a default feature because it's a relatively complicated feature to maintain? I'm simply wondering why it's not a default. 

On another topic, just thought I'd mention it in passing, that viewing/downloading the results of freetestresponse is not the most user friendly and is kind of unacceptable for non-technical instructors to view. We should, as a community, improve the way freetextresponse' responses are viewed by course teams. :)

**Comment by regisb** [comment]
> is this freetextresponse not a default feature because it's a relatively complicated feature to maintain?

The freetextresponse XBlock repository was last updated 3 years ago: https://github.com/Stanford-Online/xblock-free-text-response
I do not want to add to the default Open edX distribution packages that might go unmaintained in the future -- or are already unmaintained.

To be honest, I feel like we should not even bother testing these xblocks here. It's just not the role of the BTR to fix issues from other people's repositories. We need to fix stuff in Open edX because... well let's just say that that's how things are. But it does not mean that it's our job to detect and fix issues in other people repos, that's just setting a bad example.

**Comment by DeanJayMathew** [comment]
@regisb @sambapete thanks for the valuable insights. Let us then label (in the test sheet) which features/test cases are part of the default distribution and which are not. I will work on this and add it to the next BTR agenda for discussion.

I presume our community will continue to seek to add as many features to the default distribution as possible, but in order to do that we will need to create a health map of all the features and maintainers, then perform more community evangelism to attract/retain talent to maintain said features so that Tutor is happy to accept those features into the default distribution. Lack of standard features is a major blocker to wider adoption of the platform worldwide, a blocker to major income that could fund the community and ultimately a sustainable Open edX® community, for the people by the people. :)

**Comment by NeOneSoft** [comment]
Hi amigo @DeanJayMathew !!!, should we discuss this with the XBlocks maintainers in order to encourage them to provide support for further releases?

**Comment by arbrandes** [comment]
Closing as stale.
