### ISSUE TITLE
TC_AUTHOR_78 > Studio > Xblock > ubcpi > Xblock is not appearing under advance xblock list

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#171]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click on add unit
4. Go to advance setting under settings dropdown and then add "ubcpi" in the list and save it
5. Check ubcpi xblock under advance xblocks list
**Expected result:**
Xblock should be available under advance xblock list
**Actual result:**
Xblock is not available under advance xblock list

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by pdpinch** [comment]
although ubcpi is supported on edx.org, for some reason it is not part of the standard open edX release. 

@regisb has offered to turn it on in the test environment, so we can continue with testing.

**Comment by regisb** [comment]
I just noticed that the latest release of the ubcpi-xblock on pypi dates back from October 2020: https://pypi.org/project/ubcpi-xblock/
Is this really what we are supposed to install? How does MIT install this xblock?

**Comment by sambapete** [comment]
At EDUlib we install it from the source
https://github.com/ubc/ubcpi

**Comment by regisb** [comment]
XBlock was installed to the demo platform. See for instance: https://studio.nutmeg.demo.overhang.io/container/block-v1:edX+DemoX+Demo_Course+type@vertical+block@0a60a14e26944f5488321104e5f18b0f?action=new
See PR: https://github.com/overhangio/nutmeg-demo/pull/11

**Comment by DeanJayMathew** [comment]
I tried to follow that link (
***@***.******@***.***?action=new)
but the Nutmeg demo site appears to be down now:

https://nutmeg.demo.overhang.io/
https://studio.nutmeg.demo.overhang.io/

Dean Jay Mathew
Director, ABC Online Courses Limited

Trusted Open edX® Service Providers since 2015
Schedule a meeting with me: https://calendly.com/abconlinecourses
View Our Website <http://www.abconlinecourses.com>
WhatsApp: +447379424911 (UK)
Registered Address: Chestnut House
***@***.***,-2.1459131,15z/data=!3m1!4b1!4m8!1m2!2m1!1schestnut+house+53d+beanacre+sn127py!3m4!1s0x48717c9105a9d3d7:0x15804f821ad57207!8m2!3d51.3980641!4d-2.1374675>
(Wiltshire, England, UK)



*Legal Disclaimer: **This email and any files transmitted with it are
confidential and intended solely for the use of the individual or entity to
whom they are addressed and intended. If you have received this email in
error please notify the sender or system manager immediately. This message
contains confidential information and is intended only for the individual
named. If you are not the named addressee you should not disseminate,
distribute or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and delete this e-mail
from your system. If you are not the intended recipient you are notified
that disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.*

**Comment by regisb** [comment]
Yes, it was down while I was installing the ecommerce plugin. (See [PR](https://github.com/overhangio/nutmeg-demo/pull/12)). It's now back up.

**Comment by briangrossman** [comment]
Yup. It's appearing now. 

I tested on [Open edX Test Course](https://studio.nutmeg.demo.overhang.io/course/course-v1:TestX+Course+1)

Steps:

> * Go to advance setting under settings dropdown and then add "ubcpi" in the list and save it

![Screen Shot 2022-05-26 at 2 24 03 PM](https://user-images.githubusercontent.com/21342568/170552922-cd24e0b6-cd3d-4060-94c4-3794866bf079.png)

> * Check ubcpi xblock under advance xblocks list
>   **Expected result:**
>   Xblock should be available under advance xblock list
>   **Actual result:**
>   Xblock is not available under advance xblock list

**Before**
![Screen Shot 2022-05-26 at 2 23 46 PM](https://user-images.githubusercontent.com/21342568/170553085-b08d8b12-c938-427f-baf9-9c08fb0bc6cc.png)

**After**
![Screen Shot 2022-05-26 at 2 24 38 PM](https://user-images.githubusercontent.com/21342568/170553144-4be215a7-715a-41c3-bc63-d8bec81cac48.png)

**Comment by briangrossman** [comment]
[Example](https://preview.nutmeg.demo.overhang.io/courses/course-v1:TestX+Course+1/courseware/5c86b8c7166045878c541c4ea0b853a3/be6a5c1c790d4ef087c2acc374598073/2?activate_block_id=block-v1%3ATestX%2BCourse%2B1%2Btype%40vertical%2Bblock%40df09c5ec5aea430c91b30b422e69d637)

**Comment by BbrSofiane** [comment]
Thanks @briangrossman!

**Comment by DeanJayMathew** [comment]
Thank you, @fayyazahmed66, @pdpinch, @regisb and @briangrossman!

Does this mean this will ubcpi will be included by default Tutor installations moving forwards?

**Comment by DeanJayMathew** [comment]
I've marked this as Passed and Resolved in the test sheet.

**Comment by regisb** [comment]
> Does this mean this will ubcpi will be included by default Tutor installations moving forwards?

It is already the case, and it will continue to be like this in the future.
