### ISSUE TITLE
TC_AUTHOR_76 > Studio > Xblock > edx_saga > Xblock is not appearing under advance xblock list

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#172]
**Steps to reproduce:**

1. Go to https://studio.nutmeg.demo.overhang.io/home with staff credentials
2. Go to any course
3. Click on add unit
4. Go to advance setting under settings dropdown and then add "edx_saga" in the list and save it
5. Check edx_saga xblock under advance xblocks list
**Expected result:**
Xblock should be available under advance xblock list
**Actual result:**
Xblock is not available under advance xblock list

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by pdpinch** [comment]
According to @regisb this is due to an issue with the xBlock itself. Since MIT Open Learning is the maintainer of this xBlock. we'll take a look at this to see if we can find the problem.

**Comment by pdpinch** [comment]
@fayyazahmed66 did you add "edx_sga" to the advanced settings in your test course? This xBlock isn't available in a course until you do that (maybe this needs to be part of the test plan).

![image](https://user-images.githubusercontent.com/430126/167682462-bde4fef8-8062-4dc0-8f60-040fe5dccb16.png)

After you do that, SGA should be available in the list of "Advanced" xBlocks (not to be confused with the "Advanced" tab of "Problem" xBlocks)

![image](https://user-images.githubusercontent.com/430126/167682775-8f4d96de-5f39-451f-b2fa-faa5e0c8b13f.png)

![image](https://user-images.githubusercontent.com/430126/167682804-0e06e96b-9c9a-4359-b5d9-e67ac9416f20.png)

**Comment by DeanJayMathew** [comment]
Hi @Peter Pinch ***@***.***> I agree the test plan should include more
detailed instructions. I'll add more detailed instructions.

**Comment by fayyazahmed66** [comment]
@pdpinch  yeah, I did the same. I had added every X-block that I tested in advance setting on the course. Unfortunately, some X blocks are not appearing at my end. I have created tickets for those.

**Comment by DeanJayMathew** [comment]
@fayyazahmed66 @pdpinch 

The XBlocks that Fayyaz says are not existing, probably means they are not packaged with a a standard installation. In other words they need additional installation/configuration in order to work. For example, they might need to be configured to work with a specific AWS S3 bucket. 

I am going to take action by making it clear in the test plan which XBlocks come **pre-packaged** and which are **not pre-packaged**. I'm not 100% convinced of my wording yet "pre-packaged" but will use those terms if I don't find a better word for it. 

As I do not exactly know which are pre-packaged or not, I need to do some research first.

**Comment by pdpinch** [comment]
@fayyazahmed66 I think this issue can be closed. I was able to add an SGA block to my test course after taking the steps above, and it seems functional:

https://studio.nutmeg.demo.overhang.io/container/block-v1:MITx+Test101+2022_Spring+type@vertical+block@74922f51746940b89f3baca88c6cfd20

https://apps.nutmeg.demo.overhang.io/learning/course/course-v1:MITx+Test101+2022_Spring/block-v1:MITx+Test101+2022_Spring+type@sequential+block@7139dcabd3ba431fb2cc76b65b088572/block-v1:MITx+Test101+2022_Spring+type@vertical+block@74922f51746940b89f3baca88c6cfd20

If you agree, can  you close this? (I don't seem to have permission to close it myself)

**Comment by regisb** [comment]
I think that the error might stem from the fact that the actual xblock name is "edx_sga" and not "edx_saga".

**Comment by DeanJayMathew** [comment]
This XBlock is an extremely valuable one. It helps Open edX be more relevant for traditional education (i.e. smaller class sizes). The more we have features that are relevant to traditional classrooms experience, the wider the adoption of Open edX will be. In other words, it helps Open edX compete with Moodle, et cetera. We're still someway to go before we can confidently say Open edX is better than Moodle. This will lead to a massive shift towards more income for the community when educational institutions move over to Moodle. Just this week I got an email from someone saying they're going with Moodle because it's default features are more suited to their university needs. <-- this needs to stop happening one of these days :)

**Comment by DeanJayMathew** [comment]
p.s. we definitely need to provide all the advanced module list items into @kdmccormick's special testing course.  What do you think @kdmccormick ?

**Comment by kdmccormick** [comment]
@DeanJayMathew yes! I have tried my best to do that in this subsection, which includes a unit for each advance block type: https://apps.nutmeg.demo.overhang.io/learning/course/course-v1:TestX+Course+1/block-v1:TestX+Course+1+type@sequential+block@150d38f114ac4998a2b55f5c77ba01b3/block-v1:TestX+Course+1+type@vertical+block@15110240b079469e84f6a26ee8fbee24. The fifth unit in the at subsection is an `edx_sga` block.

There are two ways that the subsection could be improved:
1. Some blocks usages in the subsection could be configured to test more functionality. For example, the LTI block usage isn't configured to actually launch an LTI tool yet.
2. Are there any common but non-default block types that folks regularly install into their instances? If so, it could be good to install those into the test instance and add an example usage of them.
