### ISSUE TITLE
TC_INSTRUCTOR_2 > LMS > Tabs > Email and analytics tabs are missing according to test case

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#176]
**Steps to reproduce:**

1. Go to https://apps.nutmeg.demo.overhang.io/learning/course/ with valid user credentials
2. Go to instructor tab
**Expected result:**
All mentioned tabs should be visible.
**Actual result:**
email and analytics tabs are not present

**Comment by fayyazahmed66** [comment]
label: nutmeg testing

**Comment by DeanJayMathew** [comment]
Hi @fayyazahmed66 thanks for doing this test case. 

Please correct the title to TC_INSTRUCTOR_2. Now it says TC_LEARNER_2 which is wrong.

Thanks again.

**Comment by fayyazahmed66** [comment]
@DeanJayMathew  Oh, I am sorry. Title updated. Thanks for pointing out.

**Comment by DeanJayMathew** [comment]
By the way, I'm just thinking that those two tabs only appear after Instructor Bulk Email Feature, and Insights are installed/configured properly. They are not installed/configured in the Nutmeg demo platform for sure.

Let's see what the BTR Working Group members have to say about this.

I should probably take action to update the test case to mention this, and create a unique test case for each of those items, instead of bundling them together. In time I will do this, but I can't today.

**Comment by ghassanmas** [comment]
I was able to make the email tab inside the instruction tab to appear following these insturctions

> [Changing the Bulk Email Setting](https://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/bulk_email.html#id2)
> To enable or disable the bulk email feature for an Open edX site, follow these steps.
> 
> Sign in to the Django administration console for your base URL. For example, http://{your_URL}/admin.
> 
> In the Bulk_Email section, next to Bulk email flags, select Add.
> 
> To enable the bulk email feature, select the Enabled check box.
> 
> To disable the bulk email feature, clear the Enabled check box.
> 
> If you previously set REQUIRE_COURSE_EMAIL_AUTH: True, select the Require course email auth check box.
> 
> At the bottom of the page, select Save.[^1]

Note: If you enabled "Require course email auth" then you would enable it per courses, if not then the email will be enabled for all courses indifferently. 

@DeanJayMathew I would suggest that for each test case we have an optional value, **required featuers/flags** which would list or link to insturctions on how to actiavte/enable a featuer/flag that is needed in order to perform the test. The tricky thing here is that some featuer/flag cannot be enabled by an admin user (which was not the case here) it requires DevOps, intervention i.e. opening a PR on nutmeg demo. 
 
[^1]: https://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/bulk_email.html#changing-the-bulk-email-setting

**Comment by DeanJayMathew** [comment]
Hi @Ghassan Maslamani ***@***.***>

That would be great to have more details.

I will arrange a space, then coordinate with you and the other Test Team
members to fill it up.

Great job teammate. :)

**Comment by regisb** [comment]
We may have worked with Open edX too long to notice that there really is a usability issue here... It's amazing that we have to follow such a long set of instructions to enable a simple feature that should really be only a checkbox.

The same comment also applies to #164 (course visibility in catalog setting), which is a very obscure setting.

Maybe we should coordinate with the newly-created product working group to improve this UX? I think that the one big product issue with Open edX is the complexity of the platform. This particular feature toggle is a great example of platform complexity bubbling up to the UI. 

Also, in six months we will have to test these same features again, and will again face the same difficulties if we don't improve the UI.

**Comment by DeanJayMathew** [comment]
@regisb I would vote yes to rework the UI for Advanced Settings. It's so tough to use for a new user and seasoned users! :)

**Comment by DeanJayMathew** [comment]
@ghassanmas thanks for your instructions.

I also tested this feature now and it works:

<img width="579" alt="Screen Shot 2022-05-29 at 08 04 12" src="https://user-images.githubusercontent.com/9986523/170856519-69694960-0a5e-4f91-9dcb-c80ff06c2fda.png">

<img width="1009" alt="Screen Shot 2022-05-29 at 08 06 51" src="https://user-images.githubusercontent.com/9986523/170856527-fddd0a01-ba69-4bb6-a06d-86eb65fbdb3f.png">

@BbrSofiane since this works, may we please close this issue on or before 31st May 2022?

**Comment by DeanJayMathew** [comment]
p.s. I will remove "Analytics" from this test case.
