### ISSUE TITLE
Certificate doesn't show signature images with default template

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/build-test-release-wg#177]
###  Set up certificate and add three signatories with their details | TC_AUTHOR_141

When rendering a certificate with the platform default template, the signatories don't appear, this also happens when previewing the certificate from Studio -both with Honor modes-:
![image](https://user-images.githubusercontent.com/64440265/167931845-a47a3a5c-6d4b-4839-8e1d-b032cba89f52.png)

This issue was first raised on discuss by some community members -[here](https://discuss.openedx.org/t/instructor-signature-not-showing-up-on-certificate-previews/4962/)-, but they didn't get to a solution. When inspecting the certificate, I noticed this class:
![image](https://user-images.githubusercontent.com/64440265/167932179-8634e086-1fe7-4c30-9f70-e11e88fb6289.png)

After some research, I found the [PR](https://github.com/openedx/edx-platform/pull/16211) that added those lines. Along with a comment saying: _hide the fancy_, and nothing else. I was a bit hesitant because this _feels_  done on purpose. Disabling those styles seem to work:

![image](https://user-images.githubusercontent.com/64440265/167936189-93411815-5842-4d7d-a450-042da9d0a403.png)

I didn't notice this on our installations since we have a custom template set up instead of the default. Also, the Open edX docs don't mention anything about _having_ to create a custom template for this to work.

What do you think we could do?

**Comment by mariajgrimaldi** [comment]
My mistake (from the docs): 
Honor code certificates use the organization logo and signatory information, but do not include signature images, which are used only for verified certificates.

moral of the story: read the documentation.

**Comment by DeanJayMathew** [comment]
Great stuff!

Thanks for the insights!

Dean Jay Mathew
Director, ABC Online Courses Limited

Trusted Open edX® Service Providers since 2015
Schedule a meeting with me: https://calendly.com/abconlinecourses
View Our Website <http://www.abconlinecourses.com>
WhatsApp: +447379424911 (UK)
Registered Address: Chestnut House
***@***.***,-2.1459131,15z/data=!3m1!4b1!4m8!1m2!2m1!1schestnut+house+53d+beanacre+sn127py!3m4!1s0x48717c9105a9d3d7:0x15804f821ad57207!8m2!3d51.3980641!4d-2.1374675>
(Wiltshire, England, UK)



*Legal Disclaimer: **This email and any files transmitted with it are
confidential and intended solely for the use of the individual or entity to
whom they are addressed and intended. If you have received this email in
error please notify the sender or system manager immediately. This message
contains confidential information and is intended only for the individual
named. If you are not the named addressee you should not disseminate,
distribute or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and delete this e-mail
from your system. If you are not the intended recipient you are notified
that disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.*
