### ISSUE TITLE
[TC_LEARNER_41] > date and course outline pages are blank

### ISSUE THREAD

**Issue by fayyazahmed66** [openedx/build-test-release-wg#222]
**Steps to reproduce:**

1. Go to the progress page on any course in LMS
2. check the `date` and `course outline` pages

**Expected result:**
Pages should have some data in them.
**Actual result:**
Pages are blank
<img width="908" alt="progress page" src="https://user-images.githubusercontent.com/55684124/198257155-7aea121f-e88b-4b86-9d44-62f1170cbd6d.png">

### PRs

- [x] https://github.com/openedx/frontend-app-learning/pull/1009
- [x] https://github.com/openedx/frontend-app-learning/pull/1011 (Olive backport)

**Comment by fayyazahmed66** [comment]
label: olive testing

**Comment by mariajgrimaldi** [comment]
I believe this issue is related to the [learning MFE](https://github.com/openedx/frontend-app-learning/blob/5461c0816972df3ee5b0b796b42b451109eb780e/src/course-home/progress-tab/related-links/RelatedLinks.jsx#L35), since the path should be:
`/learning/course/course-v1:edX+DemoX+Demo_Course/home`
Instead of just:
`/course/course-v1:edX+DemoX+Demo_Course/home`, I don't know why this is behaving like that. Since I'm unfamiliar with MFEs, I'll tag some folks who are.
cc @arbrandes @kdmccormick

**Comment by kdmccormick** [comment]
@mariajgrimaldi hmmm, interesting. The path `/course/course-v1:edX+DemoX+Demo_Course/home` actually looks correct; it's just that the path is meant to be *relative to the root of the learning mfe*, which in our case is `https://apps.olive.overhang.io/learning`. The learning mfe makes this same assumption [in many other places](https://github.com/openedx/frontend-app-learning/blob/5461c0816972df3ee5b0b796b42b451109eb780e/src/index.jsx#L47).

So, I would expect some other step in Tutor's build pipeline to account for this by to prepending `/learning/` to the URL. I don't know exactly why that's not working here. If I had to guess, I'd bet it's a bug in the `<Hyperlink>` component from Paragon (or a bug in how we handle it), since this is the only place in the learning mfe where we use `<Hyperlink>` for an absolute path to the learning mfe.

**Comment by mariajgrimaldi** [comment]
Thanks, @kdmccormick, for the detailed explanation!

**Comment by ghassanmas** [comment]
@arbrandes @mariajgrimaldi following our yesterday meeting, this issue caught my attention, so while looking into I came out with a suggested fix here openedx/frontend-app-learning/pull/1009.  The way my fix work is by getting urls of the tabs from the state, simlair to how TabNavigation gets them, which orginally gets them from coursemetadata API.

**Comment by ghassanmas** [comment]
I tested this on production with tutor on my demo instance at olive.zaat.dev and it worked as expected, but in anycase, to debug this could you when loading the learning MFE check the network logs in for the result of this call: 

`https://LMS_BASE_URL/api/course_home/course_metadata/course-id `

For example in my demo instance I for 

`https://olive.zaat.dev/api/course_home/course_metadata/course-v1:zaatdev+101+1`

I get this 

```json
{
    "can_show_upgrade_sock": false,
    "verified_mode": null,
    "celebrations": {
        "first_section": false,
        "streak_length_to_celebrate": null,
        "streak_discount_enabled": false,
        "weekly_goal": false
    },
    "course_access": {
        "has_access": true,
        "error_code": null,
        "developer_message": null,
        "user_message": null,
        "additional_context_user_message": null,
        "user_fragment": null
    },
    "course_id": "course-v1:zaatdev+101+1",
    "is_enrolled": true,
    "is_self_paced": true,
    "is_staff": true,
    "number": "101",
    "org": "zaatdev",
    "original_user_is_staff": true,
    "start": "2022-12-05T00:00:00Z",
    "tabs": [
        {
            "tab_id": "courseware",
            "title": "Course",
            "url": "https://apps.olive.zaat.dev/learning/course/course-v1:zaatdev+101+1/home"
        },
        {
            "tab_id": "progress",
            "title": "Progress",
            "url": "https://apps.olive.zaat.dev/learning/course/course-v1:zaatdev+101+1/progress"
        },
        {
            "tab_id": "dates",
            "title": "Dates",
            "url": "https://apps.olive.zaat.dev/learning/course/course-v1:zaatdev+101+1/dates"
        },
        {
            "tab_id": "wiki",
            "title": "Wiki",
            "url": "https://olive.zaat.dev/courses/course-v1:zaatdev+101+1/course_wiki"
        },
        {
            "tab_id": "instructor",
            "title": "Instructor",
            "url": "https://olive.zaat.dev/courses/course-v1:zaatdev+101+1/instructor"
        }
    ],
    "title": "Olive Demo",
    "username": "admin",
    "user_timezone": null,
    "can_view_certificate": true
}

```

**Comment by mariajgrimaldi** [comment]
I'm not sure what's wrong with my setup then. Either way, can you add an image similar to [this one](https://github.com/openedx/build-test-release-wg/issues/222#issuecomment-1315306530)? So we have a record that it's working. Thanks again!

**Comment by ghassanmas** [comment]
I am not very good with photo editing, but here is an attempt screenshot when I hoverovered the dates in progress 
![image](https://user-images.githubusercontent.com/16361375/205924215-74a52ab6-2ea2-41da-ba43-8df16c78a717.png)

You can try it with https://olive.zaat.dev email: admin@zaat.dev password: admin

**Comment by mariajgrimaldi** [comment]
@ghassanmas thank you! ❤️
