### ISSUE TITLE
Lilac to install with Mongo 4.0

### ISSUE THREAD

**Issue by BbrSofiane** [openedx/build-test-release-wg#47]
Lilac to install with Mongo 4.0

**Comment by BbrSofiane** [comment]
@arbrandes At the last meeting, did you mention that someone at Open Craft was looking at this?

**Comment by BbrSofiane** [comment]
@arbrandes did you manage to find more information on this?

**Comment by regisb** [comment]
Looks like we need to upgrade the pymongo requirement of the configuration repo: https://github.com/openedx/build-test-release-wg/issues/63#issuecomment-836180590

**Comment by pomegranited** [comment]
@arbrandes  @BbrSofiane  I've created a task for Opencraft to do this next sprint (May 18 - June 1), so we'll post here when there's a PR ready.

@regisb 

> Looks like we need to upgrade the pymongo requirement of the configuration repo: https://github.com/openedx/build-test-release-wg/issues/63#issuecomment-836180590

We'll update pymongo as part of this too, thanks for noting this.

Our ticket description covers the following, does this look complete?

**Full description**

MongoDB 3.6 reached end of life on April 30, 2021.

However, the [openedx_native.yml playbook](https://github.com/edx/configuration/blob/master/playbooks/openedx_native.yml#L62-L63) still deploys mongodb3.6, as does the [docker playbook](https://github.com/edx/configuration/blob/master/docker/plays/mongo.yml).

You will likely also need to update [pymongo to <3.11](https://github.com/edx/configuration/blob/master/requirements/base.in#L18) as [used in edx-platform](https://github.com/edx/edx-platform/search?l=Text&q=pymongo), cf https://github.com/openedx/build-test-release-wg/issues/63.

Update these to use the [mongo_4_0 role](https://github.com/edx/configuration/tree/master/playbooks/roles/mongo_4_0), and submit the fix upstream to master.

No need to submit this change to our local release branches -- we always use externally-deployed mongodb databases, and so these changes don't affect us.

Fixes https://github.com/openedx/build-test-release-wg/issues/47.

**Completion criteria**

* PR against `edx/configuration` `master` which deploys mongo 4.0 for native and docker deployments.
* Sandbox configured to use `EDXAPP_MONGO_HOSTS: 'localhost'` so that it tests the native deployment.
* Fresh docker deployment tested locally.
* Once upstream master PR merged, ping Ned (or core committer maybe?) to get it cherry-picked into the `lilac.master` branch.
* Community communications on https://github.com/openedx/build-test-release-wg/issues/47

**Comment by regisb** [comment]
According to my own tests, Lilac runs fine on Mongodb 4.0. I upgraded a Mongodb 3.6 database (from Koa) to 4.0 and did not encounter any issue. The procedure should be the same as for the 3.4 -> 3.6 upgrade: https://docs.mongodb.com/manual/release-notes/4.0-upgrade-standalone/

1. Replace Mongodb 3.6 by Mongodb 4.0
2. Run `db.adminCommand({ setFeatureCompatibilityVersion: "4.0" })`

Note that my testing was quite superficial. I'll come back and edit this issue if I encounter any problem down the road.

**Comment by mtyaka** [comment]
I opened https://github.com/edx/configuration/pull/6416 to update mongo in the {{openedx_native.yml}} playbook to 4.0 and https://github.com/edx/configuration/pull/6420 to cherry-pick the change to the lilac branch.

Does anyone know what the status of the [docker playbook](https://github.com/edx/configuration/blob/master/docker/plays/mongo.yml) is? It's still using 3.2. I did not upgrade it since it might make more sense to remove it rather than upgrade if it's not being used anywhere.

**Comment by mtyaka** [comment]
The PRs ([1](https://github.com/edx/configuration/pull/6416), [2](https://github.com/edx/configuration/pull/6420)) that upgrade mongo to 4.0 have been merged to edx/configuration `master` and `open-release/lilac.master`. Can we close this issues or is there anything else to do @BbrSofiane @arbrandes?

**Comment by BbrSofiane** [comment]
@mtyaka Looks good to me, thanks for taking care of this!

**Comment by arbrandes** [comment]
Thanks @mtyaka! 👍🏼
