### ISSUE TITLE
[edx/configuration] Mongo 4.4 licensing issue

### ISSUE THREAD

**Issue by adzuci** [openedx/build-test-release-wg#93]
Hey BTR friends, Adam here from the edX SRE team.  I wanted to raise this here in case others have already thought about upgrading off of Mongo 4.0 or could share or help plan a valid backup methodology for Mongo 4.4.

Additional Context:

edX is running Mongo 4.0 clusters in EC2 instances which will reach EOL before we move past Maple, so we plan to upgrade.  Unfortunately, there are few backup restriction for upgrading mongo or later version. We are installing mongo community version and running backup on cloud manager. 

It seems that Mongo 4.2 or later may require us to run MongoDB enterprise and also need to run mongo agent on each node of cluster (https://docs.cloudmanager.mongodb.com/core/backup-preparations/#requirements-and-limitations) if we want to use Cloud Manager.

We can still upgrade the mongo to 4.2 but we need to keep it running with FCV 4.0 as it supports mongo community edition ( https://docs.cloudmanager.mongodb.com/core/backup-preparations/#backup-features-supported-at-present )

**Comment by regisb** [comment]
If I understand correctly:

1. Running some functionalities of backup and restore require an enterprise license in Mongodb 4.2 OR a feature compatibility version (FCV) set to 4.2.
2. edX is using these functionalities and thus is planning on upgrading but keeping FCV to 4.0.

Am I correct? Can we reasonably assume that these limitations will not affect the rest of the community, and so that they can upgrade to FCV 4.2?

**Comment by jfavellar90** [comment]
Hi @adzuci . I'm sure this is still an issue for your team (if you already proceeded with a solution, please let us know in a comment), even so, I add my opinion on this matter:

From my point of view, this is a limitation for the edX [specific use case](https://docs.cloudmanager.mongodb.com/core/backup-preparations/#backup-features-supported-at-present) (MongoDB community version + MongoDB cloud manager for backups) since I think you're managing a really big Mongo database. I'm not aware of the preferred backup method used by the community, however, in my experience operating several OpenedX installations, the backup tools offered by the Mongo community version out-of-the-box (mongodump, snapshots) have been sufficient to meet backup needs. We decided to proceed with the assumption @regisb mentioned in a previous comment for the Maple release, and so far Mongo backups haven't been raised as an issue in the community.

I proceed to close this issue, feel free to re-open it if you consider it requires further discussion.
